name: Check Runner Specs

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  show-specs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: OS and Kernel Info
        run: |
          echo "## OS and Kernel"
          uname -a
          cat /etc/os-release

      - name: CPU Info
        run: |
          echo "## CPU Info"
          lscpu

      - name: Memory Info
        run: |
          echo "## Memory Info"
          free -h
          cat /proc/meminfo | head -20

      - name: Disk Info
        run: |
          echo "## Disk Info"
          df -h
          lsblk

      - name: GPU Info
        run: |
          echo "## GPU Info"
          if command -v nvidia-smi &> /dev/null; then
            nvidia-smi
          else
            echo "No GPU detected or NVIDIA drivers not installed."
          fi

      - name: Network Info
        run: |
          echo "## Network Info"
          ip addr
          ping -c 2 google.com

      - name: List All Environment Variables
        run: |
          echo "## Environment Variables"
          printenv | sort
